"""Generate 50+ content topics across 6 pillars for the content queue."""

import json
from pathlib import Path

QUEUE_PATH = Path(__file__).parent.parent / "content-queue.jsonl"

TOPICS = [
    # === WORKFLOW (9 topics) ===
    {
        "id": "wf-001",
        "title": "How to Build an AI-Powered Spec Ad Pipeline in Under 4 Hours",
        "pillar": "workflow",
        "keywords": ["spec ad", "AI pipeline", "video production", "workflow automation"],
        "brief": "Step-by-step process for creating a spec ad from concept to final render using AI tools. Cover ideation with Claude, image gen with Flux/Midjourney, video with Kling/Runway, audio with ElevenLabs, and assembly in Premiere.",
        "posted": False,
    },
    {
        "id": "wf-002",
        "title": "Complete Workflow: AI Music Video from Concept to Final Render",
        "pillar": "workflow",
        "keywords": ["music video", "AI workflow", "video production", "creative direction"],
        "brief": "Full breakdown of producing a music video with AI — from mood boards and style frames to final color grade. Include tool choices at each stage and time estimates.",
        "posted": False,
    },
    {
        "id": "wf-003",
        "title": "My AI Product Photography Workflow That Replaced a $5K Studio Shoot",
        "pillar": "workflow",
        "keywords": ["product photography", "AI imaging", "e-commerce", "cost savings"],
        "brief": "How to generate professional product photos using Flux, inpainting, and background replacement. Compare results with traditional studio work.",
        "posted": False,
    },
    {
        "id": "wf-004",
        "title": "How I Produce 30 Social Media Videos a Month Using AI Tools",
        "pillar": "workflow",
        "keywords": ["social media", "batch production", "content creation", "AI video"],
        "brief": "Batch production workflow for short-form video content. Cover scripting with Claude, visual generation, voiceover, and bulk editing techniques.",
        "posted": False,
    },
    {
        "id": "wf-005",
        "title": "Building an Automated Podcast Clip Factory with AI",
        "pillar": "workflow",
        "keywords": ["podcast", "clip generation", "automation", "content repurposing"],
        "brief": "Workflow for automatically extracting, captioning, and reformatting podcast highlights for social distribution using AI transcription and video tools.",
        "posted": False,
    },
    {
        "id": "wf-006",
        "title": "AI Storyboarding to Final Video: A Real Production Pipeline",
        "pillar": "workflow",
        "keywords": ["storyboarding", "pre-production", "AI video", "production pipeline"],
        "brief": "Using AI for rapid storyboard generation, then converting frames to video sequences. Cover the gap between AI storyboards and production-ready footage.",
        "posted": False,
    },
    {
        "id": "wf-007",
        "title": "How to Create AI-Generated Training Videos for Corporate Clients",
        "pillar": "workflow",
        "keywords": ["training videos", "corporate", "AI production", "client work"],
        "brief": "End-to-end workflow for producing corporate training content with AI avatars, voiceover, and screen recordings. Include client approval process tips.",
        "posted": False,
    },
    {
        "id": "wf-008",
        "title": "The AI Explainer Video Pipeline: Script to Screen in 2 Hours",
        "pillar": "workflow",
        "keywords": ["explainer video", "motion graphics", "AI production", "fast turnaround"],
        "brief": "Rapid explainer video production using Claude for scripts, AI for visuals, and ElevenLabs for narration. Focus on speed without sacrificing quality.",
        "posted": False,
    },
    {
        "id": "wf-009",
        "title": "Producing AI-Enhanced Real Estate Tours: Complete Workflow Guide",
        "pillar": "workflow",
        "keywords": ["real estate", "virtual tours", "AI video", "property marketing"],
        "brief": "How to combine drone footage with AI-enhanced visuals, virtual staging, and automated voiceover for real estate marketing content.",
        "posted": False,
    },
    # === REVIEW (9 topics) ===
    {
        "id": "rv-001",
        "title": "Kling vs Runway vs Veo: Which AI Video Generator for Production Use?",
        "pillar": "review",
        "keywords": ["Kling", "Runway", "Veo", "AI video comparison", "video generation"],
        "brief": "Head-to-head comparison of the three leading AI video generators. Test with identical prompts, compare motion quality, coherence, resolution, and pricing. Include production-ready verdict.",
        "posted": False,
    },
    {
        "id": "rv-002",
        "title": "ElevenLabs vs PlayHT vs Cartesia: AI Voice Generation for Video Production",
        "pillar": "review",
        "keywords": ["ElevenLabs", "PlayHT", "Cartesia", "AI voice", "text-to-speech"],
        "brief": "Compare top AI voice generators for production use. Evaluate naturalness, language support, voice cloning quality, latency, and API pricing.",
        "posted": False,
    },
    {
        "id": "rv-003",
        "title": "Flux vs Midjourney vs DALL-E 3: AI Image Generation for Production Work",
        "pillar": "review",
        "keywords": ["Flux", "Midjourney", "DALL-E", "image generation", "production quality"],
        "brief": "Compare image generators for professional production. Focus on controllability, consistency, commercial licensing, and integration into production pipelines.",
        "posted": False,
    },
    {
        "id": "rv-004",
        "title": "Best AI Music Generators for Video Production in 2026",
        "pillar": "review",
        "keywords": ["AI music", "Suno", "Udio", "video scoring", "production music"],
        "brief": "Review Suno, Udio, and other AI music tools for scoring video content. Cover licensing, quality, customization, and how they compare to stock music.",
        "posted": False,
    },
    {
        "id": "rv-005",
        "title": "AI Video Upscaling Tools Compared: Topaz vs CapCut vs Runway",
        "pillar": "review",
        "keywords": ["video upscaling", "Topaz", "AI enhancement", "post-production"],
        "brief": "Compare AI upscaling and enhancement tools for production. Test with real footage, measure quality gains, processing times, and cost per minute.",
        "posted": False,
    },
    {
        "id": "rv-006",
        "title": "Claude vs GPT-4 vs Gemini: Which LLM for Production Scripting?",
        "pillar": "review",
        "keywords": ["Claude", "GPT-4", "Gemini", "scriptwriting", "LLM comparison"],
        "brief": "Compare LLMs specifically for production scripting tasks — ad copy, video scripts, storyboards, and creative briefs. Include prompt examples and output quality comparison.",
        "posted": False,
    },
    {
        "id": "rv-007",
        "title": "AI Subtitle and Caption Tools: Reviewed for Production Quality",
        "pillar": "review",
        "keywords": ["subtitles", "captions", "AI transcription", "accessibility"],
        "brief": "Compare AI captioning tools for production use — Whisper, CapCut auto-captions, Premiere auto-transcribe. Focus on accuracy, styling, and multilingual support.",
        "posted": False,
    },
    {
        "id": "rv-008",
        "title": "HeyGen vs Synthesia vs D-ID: AI Avatar Platforms for Client Work",
        "pillar": "review",
        "keywords": ["HeyGen", "Synthesia", "D-ID", "AI avatars", "talking head"],
        "brief": "Compare AI avatar platforms for producing client-facing content. Evaluate realism, customization, pricing tiers, and when to use vs. real presenters.",
        "posted": False,
    },
    {
        "id": "rv-009",
        "title": "The Best Free and Paid AI Tools for Solo Video Producers in 2026",
        "pillar": "review",
        "keywords": ["free tools", "solo producer", "budget", "AI toolkit"],
        "brief": "Curated toolkit for solo producers at different budget levels. Cover free tiers, best value paid tools, and the minimum viable AI production stack.",
        "posted": False,
    },
    # === BUSINESS (9 topics) ===
    {
        "id": "bz-001",
        "title": "What to Charge Clients for AI Video Production in 2026",
        "pillar": "business",
        "keywords": ["pricing", "client rates", "AI production", "business model"],
        "brief": "Practical pricing guide for AI-assisted video production. Cover hourly vs project rates, how to factor in AI tool costs, and positioning against traditional production houses.",
        "posted": False,
    },
    {
        "id": "bz-002",
        "title": "How I Built a $10K/Month AI Production Side Business",
        "pillar": "business",
        "keywords": ["side business", "revenue", "freelance", "AI production"],
        "brief": "Realistic breakdown of building an AI production business from scratch. Cover client acquisition, service packaging, delivery workflows, and monthly economics.",
        "posted": False,
    },
    {
        "id": "bz-003",
        "title": "Writing AI Production Proposals That Actually Win Clients",
        "pillar": "business",
        "keywords": ["proposals", "client acquisition", "sales", "AI production"],
        "brief": "How to write proposals for AI production work. Address client concerns about AI, show value, include sample deliverables, and structure pricing.",
        "posted": False,
    },
    {
        "id": "bz-004",
        "title": "The Real Cost of Running an AI Production Stack in 2026",
        "pillar": "business",
        "keywords": ["tool costs", "subscription management", "ROI", "production expenses"],
        "brief": "Honest breakdown of monthly costs for a professional AI production stack. Cover all subscriptions, API costs, compute, and hidden expenses. Calculate ROI against traditional methods.",
        "posted": False,
    },
    {
        "id": "bz-005",
        "title": "How to Explain AI Production to Clients Without Losing the Deal",
        "pillar": "business",
        "keywords": ["client communication", "AI transparency", "sales", "trust"],
        "brief": "Guide to discussing AI in your production process with clients. When to disclose, how to frame the value, and handling objections about authenticity.",
        "posted": False,
    },
    {
        "id": "bz-006",
        "title": "5 AI Production Services You Can Start Selling This Week",
        "pillar": "business",
        "keywords": ["services", "productization", "quick start", "AI business"],
        "brief": "Five concrete AI production services with low barriers to entry. For each: what you deliver, tools needed, time investment, and suggested pricing.",
        "posted": False,
    },
    {
        "id": "bz-007",
        "title": "Managing Client Revisions in AI Production: Setting Expectations",
        "pillar": "business",
        "keywords": ["client management", "revisions", "scope creep", "AI production"],
        "brief": "How to structure revision policies for AI-generated content. Cover the unique challenges of AI revisions vs traditional, and how to price accordingly.",
        "posted": False,
    },
    {
        "id": "bz-008",
        "title": "Legal Considerations for AI-Generated Commercial Content",
        "pillar": "business",
        "keywords": ["legal", "copyright", "licensing", "commercial use"],
        "brief": "Overview of legal landscape for AI production work. Cover copyright status, licensing requirements, client contracts, and protecting yourself.",
        "posted": False,
    },
    {
        "id": "bz-009",
        "title": "Building a Portfolio That Showcases AI Production Skills",
        "pillar": "business",
        "keywords": ["portfolio", "marketing", "personal brand", "AI production"],
        "brief": "How to build a compelling portfolio as an AI producer. What to show, how to present AI-assisted work, and platforms that work best for showcasing.",
        "posted": False,
    },
    # === CASE STUDY (8 topics) ===
    {
        "id": "cs-001",
        "title": "Case Study: Producing a 60-Second AI Commercial for Under $200",
        "pillar": "case_study",
        "keywords": ["commercial", "low budget", "AI production", "case study"],
        "brief": "Full production breakdown of creating a broadcast-quality 60s commercial with AI tools. Timeline, tool choices, costs, iterations, and final quality assessment.",
        "posted": False,
    },
    {
        "id": "cs-002",
        "title": "How We Made 50 Product Videos in One Week with AI",
        "pillar": "case_study",
        "keywords": ["batch production", "e-commerce", "product videos", "scale"],
        "brief": "Case study on batch-producing product videos for an e-commerce client. Cover the templating system, AI generation pipeline, QA process, and per-video costs.",
        "posted": False,
    },
    {
        "id": "cs-003",
        "title": "AI vs Traditional: We Produced the Same Video Both Ways — Here's What Happened",
        "pillar": "case_study",
        "keywords": ["comparison", "traditional production", "AI production", "quality"],
        "brief": "Side-by-side comparison of producing identical content with AI vs traditional methods. Cover time, cost, quality, and client reaction.",
        "posted": False,
    },
    {
        "id": "cs-004",
        "title": "Case Study: Building a YouTube Channel with 100% AI-Generated Content",
        "pillar": "case_study",
        "keywords": ["YouTube", "content creation", "AI channel", "growth"],
        "brief": "Breakdown of launching and growing a YouTube channel using entirely AI-generated content. Cover niche selection, production workflow, analytics, and monetization timeline.",
        "posted": False,
    },
    {
        "id": "cs-005",
        "title": "From Brief to Delivery in 48 Hours: AI Production Under Pressure",
        "pillar": "case_study",
        "keywords": ["fast turnaround", "client work", "deadline", "AI production"],
        "brief": "Real-world case study of delivering a rush job using AI tools. Hour-by-hour timeline, tool choices, compromises made, and client feedback.",
        "posted": False,
    },
    {
        "id": "cs-006",
        "title": "Case Study: AI-Produced Social Campaign That Got 2M Organic Views",
        "pillar": "case_study",
        "keywords": ["social media", "viral content", "campaign", "organic reach"],
        "brief": "Breakdown of an AI-produced social media campaign that performed exceptionally. Cover content strategy, production approach, posting strategy, and analytics.",
        "posted": False,
    },
    {
        "id": "cs-007",
        "title": "Rebuilding a Client's Entire Video Library with AI: Lessons Learned",
        "pillar": "case_study",
        "keywords": ["video library", "content refresh", "enterprise", "AI migration"],
        "brief": "Case study on migrating a client's outdated video content to AI-produced versions. Cover scoping, quality benchmarks, client approval process, and total savings.",
        "posted": False,
    },
    {
        "id": "cs-008",
        "title": "Case Study: AI Documentary Short — What Works and What Doesn't Yet",
        "pillar": "case_study",
        "keywords": ["documentary", "AI filmmaking", "storytelling", "limitations"],
        "brief": "Honest assessment of using AI tools for documentary-style content. What AI handles well, where it falls short, and hybrid approaches that work.",
        "posted": False,
    },
    # === INDUSTRY NEWS (8 topics) ===
    {
        "id": "nw-001",
        "title": "Runway Gen-4 Is Here: What It Means for AI Video Production",
        "pillar": "news",
        "keywords": ["Runway", "Gen-4", "AI video", "industry update"],
        "brief": "Analysis of the latest Runway release and its impact on production workflows. Cover new capabilities, pricing changes, and practical implications for producers.",
        "posted": False,
    },
    {
        "id": "nw-002",
        "title": "Google's Veo 3 Changes the Game: First Impressions for Producers",
        "pillar": "news",
        "keywords": ["Veo", "Google", "AI video", "new release"],
        "brief": "First look at Veo 3 from a production perspective. What's new, how it compares, and whether it's ready for professional use.",
        "posted": False,
    },
    {
        "id": "nw-003",
        "title": "The State of AI Video Production — March 2026 Roundup",
        "pillar": "news",
        "keywords": ["industry roundup", "AI video", "monthly update", "trends"],
        "brief": "Monthly roundup of significant developments in AI production. Cover tool releases, industry moves, pricing changes, and emerging trends.",
        "posted": False,
    },
    {
        "id": "nw-004",
        "title": "Major Studios Are Now Using AI Production Tools — Here's How",
        "pillar": "news",
        "keywords": ["major studios", "Hollywood", "AI adoption", "industry"],
        "brief": "Overview of how major studios and production companies are integrating AI tools. Cover specific use cases, public statements, and implications for independent producers.",
        "posted": False,
    },
    {
        "id": "nw-005",
        "title": "New Copyright Rulings and What They Mean for AI Producers",
        "pillar": "news",
        "keywords": ["copyright", "legal", "AI content", "regulation"],
        "brief": "Analysis of recent copyright rulings affecting AI-generated content. Practical implications for producers, what to watch out for, and protective measures.",
        "posted": False,
    },
    {
        "id": "nw-006",
        "title": "AI Production Tool Pricing Is Getting Aggressive — Q1 2026 Analysis",
        "pillar": "news",
        "keywords": ["pricing", "competition", "AI tools", "market analysis"],
        "brief": "Analysis of pricing trends across AI production tools. Who's cutting prices, who's adding value, and how this affects production economics.",
        "posted": False,
    },
    {
        "id": "nw-007",
        "title": "ElevenLabs Launches Real-Time Voice Direction — Why This Matters",
        "pillar": "news",
        "keywords": ["ElevenLabs", "voice AI", "real-time", "new feature"],
        "brief": "Analysis of ElevenLabs' latest feature and what it means for production workflows. Cover capabilities, use cases, and competitive impact.",
        "posted": False,
    },
    {
        "id": "nw-008",
        "title": "The AI Production Job Market: Who's Hiring and What They Want",
        "pillar": "news",
        "keywords": ["jobs", "careers", "AI production", "hiring trends"],
        "brief": "Survey of the emerging AI production job market. Cover in-demand skills, salary ranges, company types, and how to position yourself.",
        "posted": False,
    },
    # === TUTORIALS (9 topics) ===
    {
        "id": "tu-001",
        "title": "Step-by-Step: Creating Consistent AI Characters Across Multiple Scenes",
        "pillar": "tutorial",
        "keywords": ["character consistency", "AI imaging", "multi-scene", "tutorial"],
        "brief": "Detailed tutorial on maintaining character consistency in AI-generated content. Cover seed techniques, reference images, LoRA training, and cross-tool workflows.",
        "posted": False,
    },
    {
        "id": "tu-002",
        "title": "How to Use ControlNet for Production-Quality AI Video Compositing",
        "pillar": "tutorial",
        "keywords": ["ControlNet", "compositing", "AI video", "VFX"],
        "brief": "Technical tutorial on using ControlNet for precise video compositing. Cover depth maps, edge detection, pose estimation, and integrating results into NLE timelines.",
        "posted": False,
    },
    {
        "id": "tu-003",
        "title": "Building a Custom AI Voice for Your Production Brand",
        "pillar": "tutorial",
        "keywords": ["voice cloning", "brand voice", "ElevenLabs", "audio production"],
        "brief": "Tutorial on creating and training a custom AI voice for consistent brand narration. Cover recording requirements, training process, and fine-tuning for different content types.",
        "posted": False,
    },
    {
        "id": "tu-004",
        "title": "Mastering Prompt Engineering for AI Video Generation",
        "pillar": "tutorial",
        "keywords": ["prompt engineering", "AI video", "Runway", "Kling"],
        "brief": "Comprehensive guide to writing prompts that produce reliable, high-quality AI video. Cover structure, camera movements, style references, and common pitfalls.",
        "posted": False,
    },
    {
        "id": "tu-005",
        "title": "How to Color Grade AI-Generated Footage to Match Real Camera Footage",
        "pillar": "tutorial",
        "keywords": ["color grading", "AI footage", "DaVinci Resolve", "post-production"],
        "brief": "Tutorial on color grading AI video to seamlessly integrate with real footage. Cover LUT creation, matching color science, and dealing with AI artifacts.",
        "posted": False,
    },
    {
        "id": "tu-006",
        "title": "Automating Your AI Production Pipeline with Python and APIs",
        "pillar": "tutorial",
        "keywords": ["automation", "Python", "API", "production pipeline"],
        "brief": "Technical tutorial on building automated production pipelines with Python. Cover API integration for multiple AI tools, job queuing, and output management.",
        "posted": False,
    },
    {
        "id": "tu-007",
        "title": "Adding Realistic Camera Movement to AI-Generated Shots",
        "pillar": "tutorial",
        "keywords": ["camera movement", "AI video", "cinematography", "post-production"],
        "brief": "Tutorial on adding believable camera movement to static or minimally-moving AI video. Cover virtual camera techniques, parallax, and motion smoothing.",
        "posted": False,
    },
    {
        "id": "tu-008",
        "title": "How to Train a LoRA for Production-Specific AI Image Generation",
        "pillar": "tutorial",
        "keywords": ["LoRA", "fine-tuning", "custom training", "AI imaging"],
        "brief": "Step-by-step guide to training LoRA models for specific production needs. Cover dataset preparation, training parameters, and integration with Flux/SD workflows.",
        "posted": False,
    },
    {
        "id": "tu-009",
        "title": "Professional Audio Mixing for AI-Produced Video Content",
        "pillar": "tutorial",
        "keywords": ["audio mixing", "AI audio", "post-production", "sound design"],
        "brief": "Tutorial on mixing AI-generated audio elements (voice, music, SFX) into professional soundtracks. Cover levels, EQ, spatial audio, and delivery formats.",
        "posted": False,
    },
]


def seed():
    """Write all topics to content-queue.jsonl."""
    with open(QUEUE_PATH, "w") as f:
        for topic in TOPICS:
            f.write(json.dumps(topic) + "\n")
    print(f"Seeded {len(TOPICS)} topics to {QUEUE_PATH}")

    # Summary by pillar
    from collections import Counter
    counts = Counter(t["pillar"] for t in TOPICS)
    for pillar, count in sorted(counts.items()):
        print(f"  {pillar}: {count}")


if __name__ == "__main__":
    seed()
